name: monokle-build-windows

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [steen/housekeeping/build-binaries-windows]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Make sure build is clean and no files from a previous run are re-used.
      - name: Cleanup files before run
        run: |
          cmd /r dir
        if: ${{ always() }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Checkout Project
        uses: actions/checkout@v2

      # Install Dependencies
      - name: Install Dependencies
        run: |
          Invoke-WebRequest -Uri "https://nodejs.org/dist/v16.6.1/node-v16.6.1-x64.msi" -OutFile "nodejs.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/I .\nodejs.msi'
          cmd /r dir
          node --version

      - name: Check Dependencies
        run: |
          node --version
